tauro/blueprints/usuarios/views.py
"""
Usuarios, vistas
"""

import json
import re
from datetime import datetime

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from pytz import timezone
from lib.pwgen import generar_contrasena

from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.safe_next_url import safe_next_url
from lib.safe_string import CONTRASENA_REGEXP, EMAIL_REGEXP, safe_email, safe_message, safe_string
from tauro.extensions import pwd_context
from tauro.blueprints.bitacoras.models import Bitacora
from tauro.blueprints.entradas_salidas.models import EntradaSalida
from tauro.blueprints.modulos.models import Modulo
from tauro.blueprints.permisos.models import Permiso
from tauro.blueprints.usuarios.decorators import anonymous_required, permission_required
from tauro.blueprints.usuarios.forms import AccesoForm, UsuarioForm
from tauro.blueprints.usuarios.models import Usuario
from tauro.blueprints.ubicaciones.models import Ubicacion

MODULO = "USUARIOS"

usuarios = Blueprint("usuarios", __name__, template_folder="templates")


@usuarios.route("/login", methods=["GET", "POST"])
@anonymous_required()
def login():
    """Acceso al Sistema"""
    form = AccesoForm(siguiente=request.args.get("siguiente"))
    if form.validate_on_submit():
        # Tomar valores del formulario
        identidad = request.form.get("identidad")
        contrasena = request.form.get("contrasena")
        siguiente_url = request.form.get("siguiente")
        # El ingreso es con username/password
        if re.fullmatch(EMAIL_REGEXP, identidad) is None:
            flash("Correo electrónico no válido.", "warning")
        elif re.fullmatch(CONTRASENA_REGEXP, contrasena) is None:
            flash("Contraseña no válida.", "warning")
        else:
            usuario = Usuario.find_by_identity(identidad)
            if usuario and usuario.authenticated(password=contrasena):
                if login_user(usuario, remember=True) and usuario.is_active:
                    EntradaSalida(
                        usuario_id=usuario.id,
                        tipo="INGRESO",
                        direccion_ip=request.remote_addr,
                    ).save()
                    if siguiente_url:
                        return redirect(safe_next_url(siguiente_url))
                    return redirect(url_for("sistemas.start"))
                else:
                    flash("No está activa esa cuenta", "warning")
            else:
                flash("Usuario o contraseña incorrectos.", "warning")
    return render_template(
        "usuarios/login.jinja2",
        form=form,
        title="Sistema de Turnos",
    )


@usuarios.route("/logout")
@login_required
def logout():
    """Salir del Sistema"""
    EntradaSalida(
        usuario_id=current_user.id,
        tipo="SALIO",
        direccion_ip=request.remote_addr,
    ).save()
    logout_user()
    flash("Ha salido de este sistema.", "success")
    return redirect(url_for("usuarios.login"))


@usuarios.route("/perfil")
@login_required
def profile():
    """Mostrar el Perfil"""
    ahora_utc = datetime.now(timezone("UTC"))
    ahora_mx_coah = ahora_utc.astimezone(timezone("America/Mexico_City"))
    formato_fecha = "%Y-%m-%d %H:%M %p"
    return render_template(
        "usuarios/profile.jinja2",
        ahora_utc_str=ahora_utc.strftime(formato_fecha),
        ahora_mx_coah_str=ahora_mx_coah.strftime(formato_fecha),
    )


@usuarios.route("/usuarios/datatable_json", methods=["GET", "POST"])
@login_required
@permission_required(MODULO, Permiso.VER)
def datatable_json():
    """DataTable JSON para listado de Usuarios"""
    # Tomar parámetros de Datatables
    draw, start, rows_per_page = get_datatable_parameters()
    # Consultar
    consulta = Usuario.query
    # Primero filtrar por columnas propias
    if "estatus" in request.form:
        consulta = consulta.filter(Usuario.estatus == request.form["estatus"])
    else:
        consulta = consulta.filter(Usuario.estatus == "A")
    # Filtrar por las columnas de texto de Usuario
    if "nombres" in request.form:
        consulta = consulta.filter(Usuario.nombres.contains(safe_string(request.form["nombres"])))
    if "apellido_paterno" in request.form:
        consulta = consulta.filter(Usuario.apellido_paterno.contains(safe_string(request.form["apellido_paterno"])))
    if "apellido_materno" in request.form:
        consulta = consulta.filter(Usuario.apellido_materno.contains(safe_string(request.form["apellido_materno"])))
    if "email" in request.form:
        consulta = consulta.filter(Usuario.email.contains(safe_email(request.form["email"], search_fragment=True)))
    if "unidad_id" in request.form:
        consulta = consulta.filter(Usuario.unidad_id == request.form["unidad_id"])
    # Ordenar y paginar
    registros = consulta.order_by(Usuario.email).offset(start).limit(rows_per_page).all()
    total = consulta.count()
    # Elaborar datos para DataTable
    data = []
    for resultado in registros:
        data.append(
            {
                "id": resultado.id,
                "detalle": {
                    "email": resultado.email,
                    "url": url_for("usuarios.detail", usuario_id=resultado.id),
                },
                "nombre": resultado.nombre,
                "ubicacion": {
                    "nombre": resultado.ubicacion.nombre_numero,
                    "url": url_for("ubicaciones.detail", ubicacion_id=resultado.ubicacion.id),
                },
                "acceso_frontend": resultado.es_acceso_frontend,
            }
        )
    # Entregar JSON
    return output_datatable_json(draw, total, data)


@usuarios.route("/usuarios")
@login_required
@permission_required(MODULO, Permiso.VER)
def list_active():
    """Listado de Usuarios activos"""
    return render_template(
        "usuarios/list.jinja2",
        filtros=json.dumps({"estatus": "A"}),
        titulo="Usuarios",
        estatus="A",
    )


@usuarios.route("/usuarios/inactivos")
@login_required
@permission_required(MODULO, Permiso.ADMINISTRAR)
def list_inactive():
    """Listado de Usuarios inactivos"""
    return render_template(
        "usuarios/list.jinja2",
        filtros=json.dumps({"estatus": "B"}),
        titulo="Usuarios inactivos",
        estatus="B",
    )


@usuarios.route("/usuarios/<int:usuario_id>")
@login_required
@permission_required(MODULO, Permiso.VER)
def detail(usuario_id):
    """Detalle de un Usuario"""
    usuario = Usuario.query.get_or_404(usuario_id)
    return render_template("usuarios/detail.jinja2", usuario=usuario)


@usuarios.route("/usuarios/nuevo", methods=["GET", "POST"])
@login_required
@permission_required(MODULO, Permiso.CREAR)
def new():
    """Nuevo Usuario"""
    form = UsuarioForm()
    if form.validate_on_submit():
        # Validaciones
        es_valido = True
        # Validar que el email no se repita
        email = safe_email(form.email.data)
        if Usuario.query.filter_by(email=email).first():
            flash("El e-mail ya está en uso. Debe de ser único.", "warning")
            es_valido = False
        if form.contrasena.data:
            contrasena = pwd_context.hash(form.contrasena.data.strip())
        else:
            contrasena = pwd_context.hash(generar_contrasena())
        # Determinar Ubicacion como NO DEFINIDO
        ubicacion_nd = Ubicacion.query.filter_by(nombre="NO DEFINIDO").first()
        # Guardar
        if es_valido:
            usuario = Usuario(
                email=email,
                nombres=safe_string(form.nombres.data, save_enie=True),
                apellido_paterno=safe_string(form.apellido_paterno.data, save_enie=True),
                apellido_materno=safe_string(form.apellido_materno.data, save_enie=True),
                contrasena=contrasena,
                unidad_id=form.unidad.data,
                es_acceso_frontend=form.es_acceso_frontend.data,
                ubicacion=ubicacion_nd,
            )
            usuario.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Nuevo Usuario {usuario.email}"),
                url=url_for("usuarios.detail", usuario_id=usuario.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    # Entregar
    return render_template("usuarios/new.jinja2", form=form)


@usuarios.route("/usuarios/edicion/<int:usuario_id>", methods=["GET", "POST"])
@login_required
@permission_required(MODULO, Permiso.MODIFICAR)
def edit(usuario_id):
    """Editar Usuario"""
    usuario = Usuario.query.get_or_404(usuario_id)
    form = UsuarioForm()
    if form.validate_on_submit():
        es_valido = True
        # Si cambia el e-mail verificar que no este en uso
        email = safe_email(form.email.data)
        if usuario.email != email:
            usuario_existente = Usuario.query.filter_by(email=email).first()
            if usuario_existente and usuario_existente.id != usuario.id:
                es_valido = False
                flash("La e-mail ya está en uso. Debe de ser único.", "warning")
        # Verificar que la ubicacion seleccionada no este siendo utilizada por alguien más.
        ubicacion_seleccionada_id = form.ubicacion.data
        usuario_ocupando_ubicacion = Usuario.query.filter_by(ubicacion_id=ubicacion_seleccionada_id).first()
        if (
            usuario_ocupando_ubicacion
            and usuario_ocupando_ubicacion.ubicacion.nombre != "NO DEFINIDO"
            and usuario_ocupando_ubicacion.id != usuario.id
        ):
            es_valido = False
            flash(

tauro/blueprints/usuarios/templates/usuarios/edit.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Editar Usuario {{ usuario.email }}{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Editar Usuario ' + usuario.email) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'usuario_id': usuario.id} %}
        {% call f.form_tag('usuarios.edit', fid='usuario_form', **form_kwargs) %}
            {% call f.form_group(form.email) %}{% endcall %}
            {% call f.form_group(form.nombres) %}{% endcall %}
            {% call f.form_group(form.apellido_paterno) %}{% endcall %}
            {% call f.form_group(form.apellido_materno) %}{% endcall %}
            {% call f.form_group(form.contrasena) %}{% endcall %}
            {% call f.form_group(form.unidad) %}{% endcall %}
            {% call f.form_group(form.ubicacion) %}{% endcall %}
            {% call f.form_group(form.es_acceso_frontend) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

tauro/blueprints/usuarios/templates/usuarios/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}{{ titulo }}{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {% if current_user.can_view('MODULOS') %}
            {{ topbar.button('Módulos', url_for('modulos.list_active'), 'mdi:toy-brick') }}
        {% endif %}
        {% if current_user.can_view('ROLES') %}
            {{ topbar.button('Roles', url_for('roles.list_active'), 'mdi:gamepad') }}
        {% endif %}
        {% if current_user.can_admin('USUARIOS') %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivos', url_for('usuarios.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activos', url_for('usuarios.list_active')) }}{% endif %}
        {% endif %}
        {% if current_user.can_insert('USUARIOS') %}
            {{ topbar.button_new('Nuevo Usuario', url_for('usuarios.new')) }}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <!-- Filtros usuarios -->
        <div class="row">
            <div class="col">
                <form class="row g-1 mb-3" id="filtradorForm" onsubmit="filtrosDTUsuarios.buscar(); return false;">
                    <div class="col-3">
                        <div class="form-floating">
                            <input id="filtroEMail" type="text" class="form-control" aria-label="Correo electrónico">
                            <label for="filtroEMail">Correo electrónico</label>
                        </div>
                    </div>
                    <div class="col-3">
                        <div class="form-floating">
                            <input id="filtroNombres" type="text" class="form-control" aria-label="Nombres" style="text-transform: uppercase;">
                            <label for="filtroNombres">Nombres</label>
                        </div>
                    </div>
                    <div class="col-3">
                        <div class="form-floating">
                            <input id="filtroApellidoPaterno" type="text" class="form-control" aria-label="Apellido paterno" style="text-transform: uppercase;">
                            <label for="filtroApellidoPaterno">Apellido paterno</label>
                        </div>
                    </div>
                    <div class="col-3 text-end">
                        <button title="Buscar" class="btn btn-primary btn-lg" onclick="filtrosDTUsuarios.buscar(); return false;" id="button-buscar"><span class="iconify" data-icon="mdi:magnify"></span></button>
                        <button title="Limpiar" class="btn btn-warning btn-lg" type="reset" onclick="filtrosDTUsuarios.limpiar();" id="button-limpiar"><span class="iconify" data-icon="mdi:broom"></span></button>
                    </div>
                </form>
            </div>
        </div>
        <!-- Datatable usuarios -->
        <table id="usuarios_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Correo electrónico</th>
                    <th>Nombre completo</th>
                    <th>Ubicacion</th>
                    <th>Acceso al Frontend</th>
                </tr>
            </thead>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    <script src="{{ url_for('static', filename='js/datatables-constructor.js') }}"></script>
    <script src="{{ url_for('static', filename='js/datatables-filtros.js') }}"></script>
    <script>
        // DataTable usuarios
        const constructorDataTable = new ConfigDataTable( '{{ csrf_token() }}' );
        let configDTUsuarios = constructorDataTable.config();
        configDTUsuarios['ajax']['url'] = '{{ url_for("usuarios.datatable_json") }}';
        configDTUsuarios['ajax']['data'] = {{ filtros }};
        configDTUsuarios['columns'] = [
            { data: "id" },
            { data: "detalle" },
            { data: "nombre" },
            { data: "ubicacion" },
            { data: "acceso_frontend" }
        ];
        configDTUsuarios['columnDefs'] = [
            {
                targets: 1, // detalle
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.email + '</a>';
                }
            },
            {
                targets: 2, // nombre
                data: null,
                render: function(data, type, row, meta) {
                    if (data.length > 24) {
                        return '<span title="' + data + '">' + data.substring(0, 24) + '…</span>';
                    }
                    return data;
                }
            },
            {
                targets: 3, // ubicacion
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.nombre + '</a>';
                }
            },
            {
                targets: 4, // acceso_frontend
                data: null,
                render: function(data, type, row, meta) {
                    if (data) {
                        return '<span class="iconify" data-icon="mdi:checkbox-marked" style="font-size: 1.4em"></span>';
                    }
                    return '<span class="iconify text-secondary" data-icon="mdi:checkbox-blank-outline" style="font-size: 1.4em"></span>';
                }
            }
        ];
        // Filtros usuarios
        const filtrosDTUsuarios = new FiltrosDataTable('#usuarios_datatable', configDTUsuarios);
        filtrosDTUsuarios.agregarInput('filtroEMail', 'email');
        filtrosDTUsuarios.agregarInput('filtroNombres', 'nombres');
        filtrosDTUsuarios.agregarInput('filtroApellidoPaterno', 'apellido_paterno');
        filtrosDTUsuarios.precargar();
    </script>
{% endblock %}

tauro/blueprints/usuarios/templates/usuarios/login.jinja2
{% extends 'layouts/login.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}

{% block title %}{{ title }}{% endblock %}

{% block welcome %}
    <div id="welcome" class="text-center">
        <p><img class="img-fluid" src="https://storage.googleapis.com/pjecz-informatica/static/images/logo-login.png" alt="PJECZ"></p>
        <h4 class="mb-3">{{ title }}</h4>
    </div>
{% endblock %}

{% block content %}
    <div id="access" class="py-2">
        {% call f.form_tag('usuarios.login', fid='access_form') %}
            <div id="access-form-password" class="my-2">
                <div class="form-floating">
                    {% call f.field(form.identidad, id='username', class='form-control', autofocus='autofocus') %}{% endcall %}
                    <label for="username">Usuario</label>
                </div>
                <div class="form-floating">
                    {% call f.field(form.contrasena, id='password', class='form-control') %}{% endcall %}
                    <label for="password">Contraseña</label>
                </div>
                <button id="access-form-password-submit" class="w-100 btn btn-lg btn-primary my-2" type="submit">Ingresar</button>
            </div>
        {% endcall %}
    </div>
{% endblock %}

{% block custom_javascript %}
{% endblock %}

tauro/blueprints/usuarios/templates/usuarios/new.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Nuevo Usuario{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Nuevo Usuario') }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% call f.form_tag('usuarios.new', fid='usuario_form') %}
            {% call f.form_group(form.email) %}{% endcall %}
            {% call f.form_group(form.nombres) %}{% endcall %}
            {% call f.form_group(form.apellido_paterno) %}{% endcall %}
            {% call f.form_group(form.apellido_materno) %}{% endcall %}
            {% call f.form_group(form.contrasena) %}{% endcall %}
            {% call f.form_group(form.unidad) %}{% endcall %}
            {% call f.form_group(form.es_acceso_frontend) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

tauro/blueprints/usuarios/templates/usuarios/profile.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Mi Perfil{% endblock %}

{% block topbar_actions %}
    {{ topbar.page(current_user.nombre) }}
{% endblock %}

{% block content %}
    {% call detail.card('Mi Perfil') %}
        {{ detail.label_value_big('Nombre', current_user.nombre) }}
        {{ detail.label_value('CURP', current_user.curp) }}
        {{ detail.label_value('e-mail', current_user.email) }}
    {% endcall %}
    {% call detail.card('Sistema') %}
        {{ detail.label_value('Hoy UTC', ahora_utc_str) }}
        {{ detail.label_value('Hoy MX Coahuila', ahora_mx_coah_str) }}
    {% endcall %}
{% endblock %}