tauro/blueprints/modulos/views.py
"""
Modulos, vistas
"""

import json

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.safe_string import safe_message, safe_string
from tauro.blueprints.bitacoras.models import Bitacora

from tauro.blueprints.modulos.forms import ModuloForm
from tauro.blueprints.modulos.models import Modulo
from tauro.blueprints.permisos.models import Permiso
from tauro.blueprints.usuarios.decorators import permission_required

MODULO = "MODULOS"

modulos = Blueprint("modulos", __name__, template_folder="templates")


@modulos.before_request
@login_required
@permission_required(MODULO, Permiso.VER)
def before_request():
    """Permiso por defecto"""


@modulos.route("/modulos/datatable_json", methods=["GET", "POST"])
def datatable_json():
    """DataTable JSON para listado de Modulos"""
    # Tomar parámetros de Datatables
    draw, start, rows_per_page = get_datatable_parameters()
    # Consultar
    consulta = Modulo.query
    # Primero filtrar por columnas propias
    if "estatus" in request.form:
        consulta = consulta.filter_by(estatus=request.form["estatus"])
    else:
        consulta = consulta.filter_by(estatus="A")
    if "nombre" in request.form:
        nombre = safe_string(request.form["nombre"], save_enie=True)
        if nombre != "":
            consulta = consulta.filter(Modulo.nombre.contains(nombre))
    # Ordenar y paginar
    registros = consulta.order_by(Modulo.nombre).offset(start).limit(rows_per_page).all()
    total = consulta.count()
    # Elaborar datos para DataTable
    data = []
    for resultado in registros:
        data.append(
            {
                "detalle": {
                    "nombre": resultado.nombre,
                    "url": url_for("modulos.detail", modulo_id=resultado.id),
                },
                "icono": resultado.icono,
                "en_navegacion": resultado.en_navegacion,
            }
        )
    # Entregar JSON
    return output_datatable_json(draw, total, data)


@modulos.route("/modulos")
def list_active():
    """Listado de Modulos activos"""
    return render_template(
        "modulos/list.jinja2",
        filtros=json.dumps({"estatus": "A"}),
        titulo="Módulos",
        estatus="A",
    )


@modulos.route("/modulos/inactivos")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def list_inactive():
    """Listado de Modulos inactivos"""
    return render_template(
        "modulos/list.jinja2",
        filtros=json.dumps({"estatus": "B"}),
        titulo="Módulos inactivos",
        estatus="B",
    )


@modulos.route("/modulos/<int:modulo_id>")
def detail(modulo_id):
    """Detalle de un Modulo"""
    modulo = Modulo.query.get_or_404(modulo_id)
    return render_template("modulos/detail.jinja2", modulo=modulo)


@modulos.route("/modulos/nuevo", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.CREAR)
def new():
    """Nuevo Modulo"""
    form = ModuloForm()
    if form.validate_on_submit():
        # Validar que el nombre no se repita
        nombre = safe_string(form.nombre.data, save_enie=True)
        if Modulo.query.filter_by(nombre=nombre).first():
            flash("El nombre ya está en uso. Debe de ser único.", "warning")
            return render_template("modulos/new.jinja2", form=form)
        # Guardar
        modulo = Modulo(
            nombre=nombre,
            nombre_corto=safe_string(form.nombre_corto.data, do_unidecode=False, to_uppercase=False, save_enie=True),
            icono=form.icono.data,
            ruta=form.ruta.data,
            en_navegacion=form.en_navegacion.data,
        )
        modulo.save()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Nuevo Modulo {modulo.nombre}"),
            url=url_for("modulos.detail", modulo_id=modulo.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    return render_template("modulos/new.jinja2", form=form)


@modulos.route("/modulos/edicion/<int:modulo_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.MODIFICAR)
def edit(modulo_id):
    """Editar Modulo"""
    modulo = Modulo.query.get_or_404(modulo_id)
    form = ModuloForm()
    if form.validate_on_submit():
        es_valido = True
        # Si cambia el nombre verificar que no este en uso
        nombre = safe_string(form.nombre.data, save_enie=True)
        if modulo.nombre != nombre:
            modulo_existente = Modulo.query.filter_by(nombre=nombre).first()
            if modulo_existente and modulo_existente.id != modulo.id:
                es_valido = False
                flash("El nombre ya está en uso. Debe de ser único.", "warning")
        # Si es valido actualizar
        if es_valido:
            modulo.nombre = nombre
            modulo.nombre_corto = safe_string(form.nombre_corto.data, do_unidecode=False, to_uppercase=False, save_enie=True)
            modulo.icono = form.icono.data
            modulo.ruta = form.ruta.data
            modulo.en_navegacion = form.en_navegacion.data
            modulo.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Editado Modulo {modulo.nombre}"),
                url=url_for("modulos.detail", modulo_id=modulo.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    form.nombre.data = modulo.nombre
    form.nombre_corto.data = modulo.nombre_corto
    form.icono.data = modulo.icono
    form.ruta.data = modulo.ruta
    form.en_navegacion.data = modulo.en_navegacion
    return render_template("modulos/edit.jinja2", form=form, modulo=modulo)


@modulos.route("/modulos/eliminar/<int:modulo_id>")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def delete(modulo_id):
    """Eliminar Modulo"""
    este_modulo = Modulo.query.get_or_404(modulo_id)
    if este_modulo.estatus == "A":
        # Dar de baja el modulo
        este_modulo.delete()
        # Dar de baja los permisos asociados
        for permiso in este_modulo.permisos:
            permiso.delete()
        # Guardar en la bitacora
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Eliminado Modulo {este_modulo.nombre}"),
            url=url_for("modulos.detail", modulo_id=este_modulo.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("modulos.detail", modulo_id=este_modulo.id))


@modulos.route("/modulos/recuperar/<int:modulo_id>")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def recover(modulo_id):
    """Recuperar Modulo"""
    este_modulo = Modulo.query.get_or_404(modulo_id)
    if este_modulo.estatus == "B":
        # Dar de alta el modulo
        este_modulo.recover()
        # Dar de alta los permisos asociados
        for permiso in este_modulo.permisos:
            permiso.recover()
        # Guardar en la bitacora
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Recuperado Modulo {este_modulo.nombre}"),
            url=url_for("modulos.detail", modulo_id=este_modulo.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("modulos.detail", modulo_id=este_modulo.id))


@modulos.route("/modulos/select2_json", methods=["POST"])
def select2_json():
    """Proporcionar el JSON de modulos para elegir con un Select2, se usa para filtrar en DataTables"""
    consulta = Modulo.query.filter(Modulo.estatus == "A")
    if "searchString" in request.form:
        nombre = safe_string(request.form["searchString"], save_enie=True)
        if nombre != "":
            consulta = consulta.filter(Modulo.nombre.contains(nombre))
    resultados = []
    for modulo in consulta.order_by(Modulo.nombre).limit(10).all():
        resultados.append({"id": modulo.id, "text": modulo.nombre})
    return {"results": resultados, "pagination": {"more": False}}

tauro/blueprints/modulos/templates/modulos/detail.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail %}
{% import 'macros/modals.jinja2' as modals %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Módulo {{ modulo.nombre }}{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Módulo ' + modulo.nombre) %}
        {{ topbar.button_previous('Módulos', url_for('modulos.list_active')) }}
        {% if current_user.can_edit('MODULOS') %}
            {{ topbar.button_edit('Editar', url_for('modulos.edit', modulo_id=modulo.id)) }}
        {% endif %}
        {% if current_user.can_admin('MODULOS') %}
            {% if modulo.estatus == 'A' %}{{ topbar.button_delete('Eliminar', url_for('modulos.delete', modulo_id=modulo.id)) }}{% endif %}
            {% if modulo.estatus == 'B' %}{{ topbar.button_recover('Recuperar', url_for('modulos.recover', modulo_id=modulo.id)) }}{% endif %}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call detail.card(estatus=modulo.estatus) %}
        <div class="row">
            {{ detail.label_value('Nombre en menú', modulo.nombre_corto) }}
            {{ detail.label_value('Icono', modulo.icono + ' <span class="iconify" data-icon="' + modulo.icono +'"></span>') }}
            {{ detail.label_value('Ruta', modulo.ruta) }}
            {{ detail.label_value_boolean('En menú de navegación', modulo.en_navegacion) }}
        </div>
    {% endcall %}
    {% if current_user.can_view('PERMISOS') and modulo.estatus == 'A' %}
        {% call detail.card('Permisos') %}
            <!-- Datatable Permisos -->
            <table id="permisos_datatable" class="table display nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Rol</th>
                    </tr>
                </thead>
            </table>
            {% if current_user.can_insert('PERMISOS') %}
            <a href="{{ url_for('permisos.new_with_modulo', modulo_id=modulo.id) }}" class="btn btn-primary">Agregar</a>
            {% endif %}
        {% endcall %}
    {% endif %}
{% endblock %}

{% block custom_javascript %}
    {% if current_user.can_admin('MODULOS') %}
        {% if modulo.estatus == 'A' %}{{ modals.custom_javascript_delete('Eliminar', '¿Eliminar a ' + modulo.nombre + '?') }}{% endif %}
        {% if modulo.estatus == 'B' %}{{ modals.custom_javascript_recover('Recuperar', '¿Recuperar a ' + modulo.nombre + '?') }}{% endif %}
    {% endif %}
    <script src="{{ url_for('static', filename='js/datatables-constructor.js') }}"></script>
    <script src="{{ url_for('static', filename='js/datatables-filtros.js') }}"></script>
    {% if current_user.can_view('PERMISOS') %}
        <script>
            // DataTable Permisos
            const constructorDataTable = new ConfigDataTable( '{{ csrf_token() }}' );
            let configDTPermisos = constructorDataTable.config();
            configDTPermisos['ajax']['url'] = '{{ url_for("permisos.datatable_json") }}';
            configDTPermisos['ajax']['data'] = { 'estatus': "A", 'modulo_id': {{ modulo.id}} };
            configDTPermisos['columns'] = [
                { data: "detalle" },
                { data: "rol" }
            ];
            configDTPermisos['columnDefs'] = [
                {
                    targets: 0, // detalle
                    data: null,
                    render: function(data, type, row, meta) {
                        return '<a href="' + data.url + '">' + data.nombre + '</a>';
                    }
                },
                {
                    targets: 1, // rol
                    data: null,
                    render: function(data, type, row, meta) {
                        if (data.url == '') {
                            return data.nombre;
                        } else {
                            return '<a href="' + data.url + '">' + data.nombre + '</a>';
                        }
                    }
                }
            ];
            // Filtros Permisos
            const filtrosDTPermisos = new FiltrosDataTable('#permisos_datatable', configDTPermisos);
            filtrosDTPermisos.precargar();
        </script>
    {% endif %}
{% endblock %}

tauro/blueprints/modulos/templates/modulos/edit.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Editar Módulo {{ modulo.nombre_corto }}{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Editar Módulo ' + modulo.nombre_corto) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'modulo_id': modulo.id} %}
        {% call f.form_tag('modulos.edit', fid='modulo_form', **form_kwargs) %}
            {% call f.form_group(form.nombre) %}{% endcall %}
            {% call f.form_group(form.nombre_corto) %}{% endcall %}
            {% call f.form_group(form.icono) %}{% endcall %}
            {% call f.form_group(form.ruta) %}{% endcall %}
            {% call f.form_group(form.en_navegacion) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

tauro/blueprints/modulos/templates/modulos/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Módulos{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {% if current_user.can_view('ROLES') %}
            {{ topbar.button('Roles', url_for('roles.list_active'), 'mdi:gamepad') }}
        {% endif %}
        {% if current_user.can_view('USUARIOS') %}
            {{ topbar.button('Usuarios', url_for('usuarios.list_active'), 'mdi:account-key') }}
        {% endif %}
        {% if current_user.can_admin('MODULOS') %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivos', url_for('modulos.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activos', url_for('modulos.list_active')) }}{% endif %}
        {% endif %}
        {% if current_user.can_insert('MODULOS') %}
            {{ topbar.button_new('Nuevo Módulo', url_for('modulos.new')) }}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <!-- Filtros modulos -->
        <div class="row">
            <div class="col">
                <form class="row g-1 mb-3" id="filtradorForm" onsubmit="filtrosModulos.buscar(); return false;">
                    <div class="col-6">
                        <div class="form-floating">
                            <input id="filtroModuloNombre" type="text" class="form-control" aria-label="Nombre" style="text-transform: uppercase;">
                            <label for="filtroModuloNombre">Nombre</label>
                        </div>
                    </div>
                    <div class="col-6 text-end">
                        <button title="Buscar" class="btn btn-primary btn-lg" onclick="filtrosModulos.buscar(); return false;" id="button-buscar"><span class="iconify" data-icon="mdi:magnify"></span></button>
                        <button title="Limpiar" class="btn btn-warning btn-lg" type="reset" onclick="filtrosModulos.limpiar();" id="button-limpiar"><span class="iconify" data-icon="mdi:broom"></span></button>
                    </div>
                </form>
            </div>
        </div>
        <!-- Datatable modulos -->
        <table id="modulos_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Icono</th>
                    <th>En menú</th>
                </tr>
            </thead>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    <script src="{{ url_for('static', filename='js/datatables-constructor.js') }}"></script>
    <script src="{{ url_for('static', filename='js/datatables-filtros.js') }}"></script>
    <script>
        // DataTable modulos
        const constructorDataTable = new ConfigDataTable( '{{ csrf_token() }}' );
        let configDataTable = constructorDataTable.config();
        configDataTable['ajax']['url'] = '{{ url_for("modulos.datatable_json") }}';
        configDataTable['ajax']['data'] = {{ filtros }};
        configDataTable['columns'] = [
            { data: 'detalle' },
            { data: 'icono' },
            { data: 'en_navegacion' }
        ];
        configDataTable['columnDefs'] = [
            {
                targets: 0, // detalle
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.nombre + '</a>';
                }
            },
            {
                targets: 1, // icono
                data: null,
                render: function(data, type, row, meta) {
                    return '<span class="iconify" data-icon="' + data + '" style="font-size: 1.4em"></span>';
                }
            },
            {
                targets: 2, // en_navegacion
                data: null,
                render: function(data, type, row, meta) {
                    if (data) {
                        return '<span class="iconify" data-icon="mdi:checkbox-marked" style="font-size: 1.4em"></span>';
                    }
                    return '<span class="iconify text-secondary" data-icon="mdi:checkbox-blank-outline" style="font-size: 1.4em"></span>';
                }
            }
        ];
        // Filtros modulos
        const filtrosModulos = new FiltrosDataTable('#modulos_datatable', configDataTable);
        filtrosModulos.agregarInput('filtroModuloNombre', 'nombre');
        filtrosModulos.precargar();
    </script>
{% endblock %}

tauro/blueprints/modulos/templates/modulos/new.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Nuevo Módulo{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Nuevo Módulo') }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% call f.form_tag('modulos.new', fid='modulo_form') %}
            {% call f.form_group(form.nombre) %}{% endcall %}
            {% call f.form_group(form.nombre_corto) %}{% endcall %}
            {% call f.form_group(form.icono) %}{% endcall %}
            {% call f.form_group(form.ruta) %}{% endcall %}
            {% call f.form_group(form.en_navegacion) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}